// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRQFs_SKqKt_LEhKZLv62-rJdb5UX0cpM',
    appId: '1:790695937165:web:149d21d62f7c81a7d74ec4',
    messagingSenderId: '790695937165',
    projectId: 'liftdedo-8de4a',
    authDomain: 'liftdedo-8de4a.firebaseapp.com',
    storageBucket: 'liftdedo-8de4a.appspot.com',
    measurementId: 'G-ZVWZV65N6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGeWtLdH1fzp_eBJwpnd_38t0yjPBahmQ',
    appId: '1:790695937165:android:be2bc9a3b3c70e23d74ec4',
    messagingSenderId: '790695937165',
    projectId: 'liftdedo-8de4a',
    storageBucket: 'liftdedo-8de4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKxu7arfiEGsxJp5bKCOqTLoJPU6CMcyc',
    appId: '1:790695937165:ios:677c9e915b2f4467d74ec4',
    messagingSenderId: '790695937165',
    projectId: 'liftdedo-8de4a',
    storageBucket: 'liftdedo-8de4a.appspot.com',
    androidClientId: '790695937165-1tkdj3sqadg5nc86ddj7mdav35bm7gs6.apps.googleusercontent.com',
    iosClientId: '790695937165-beitd5n1ecf2ad1e163284gc0rp1m1l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.liftdedo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKxu7arfiEGsxJp5bKCOqTLoJPU6CMcyc',
    appId: '1:790695937165:ios:677c9e915b2f4467d74ec4',
    messagingSenderId: '790695937165',
    projectId: 'liftdedo-8de4a',
    storageBucket: 'liftdedo-8de4a.appspot.com',
    androidClientId: '790695937165-1tkdj3sqadg5nc86ddj7mdav35bm7gs6.apps.googleusercontent.com',
    iosClientId: '790695937165-beitd5n1ecf2ad1e163284gc0rp1m1l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.liftdedo',
  );
}
